const paises = [
    { n: "ÁUSTRIA", id: "at", img: "austria_m.png" }, 
    { n: "BÉLGICA", id: "be", img: "belgica_m.png" },
    { n: "BULGÁRIA", id: "bg", img: "bulgaria_m.png" }, 
    { n: "CROÁCIA", id: "hr", img: "croacia_m.png" },
    { n: "CHIPRE", id: "cy", img: "chipre_m.png" }, 
    { n: "CHÉQUIA", id: "cz", img: "chequia_m.png" },
    { n: "DINAMARCA", id: "dk", img: "dinamarca_m.png" }, 
    { n: "ESTÓNIA", id: "ee", img: "estonia_m.png" },
    { n: "FINLÂNDIA", id: "fi", img: "finlandia_m.png" }, 
    { n: "FRANÇA", id: "fr", img: "franca_m.png" },
    { n: "ALEMANHA", id: "de", img: "alemanha_m.png" }, 
    { n: "GRÉCIA", id: "gr", img: "grecia_m.png" },
    { n: "HUNGRIA", id: "hu", img: "hungria_m.png" }, 
    { n: "IRLANDA", id: "ie", img: "irlanda_m.png" },
    { n: "ITÁLIA", id: "it", img: "italia_m.png" }, 
    { n: "LETÓNIA", id: "lv", img: "letonia_m.png" },
    { n: "LITUÂNIA", id: "lt", img: "lituania_m.png" }, 
    { n: "LUXEMBURGO", id: "lu", img: "luxemburgo_m.png" },
    { n: "MALTA", id: "mt", img: "malta_m.png" }, 
    { n: "PAÍSES BAIXOS", id: "nl", img: "paisesbaixos_m.png" },
    { n: "POLÓNIA", id: "pl", img: "polonia_m.png" }, 
    { n: "PORTUGAL", id: "pt", img: "portugal_m.png" },
    { n: "ROMÉNIA", id: "ro", img: "romenia_m.png" }, 
    { n: "ESLOVÁQUIA", id: "sk", img: "eslovaquia_m.png" },
    { n: "ESLOVÉNIA", id: "si", img: "eslovenia_m.png" }, 
    { n: "ESPANHA", id: "es", img: "espanha_m.png" },
    { n: "SUÉCIA", id: "se", img: "suecia_m.png" }
];
